Running "module reset". Resetting modules to system default. The following $MODULEPATH directories have been removed: None
/sw/spack/deltas11-2023-03/apps/linux-rhel8-zen3/gcc-11.4.0/cuda-11.8.0-vfixfmc
11.3
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
[19:47:30] Starting script
[19:47:30] numpy imported in 0.57s
[19:47:34] torch imported in 3.43s
[19:47:34] tqdm imported in 0.00s
[19:47:34] data_structures imported in 0.93s
[19:47:35] vocab imported in 0.11s
[19:47:35] knnlm_func imported in 0.07s
[19:47:35] Starting dataset load
[19:47:36] Dataset loaded in 1.74s
[19:47:36] Starting dstore load
load index
[19:47:44] Dstore loaded in 7.15s
[19:47:44] Starting dstore load
[19:47:44] Cache loaded in 0.00s
[19:47:44] Loading exact distances
[19:47:44] Exact distances loaded in 0.02s
[19:47:44] Loading dictionary
[19:47:44] Dictionary loaded in 0.58s
[19:47:44] found 267744 tokens in vocab data-bin/wikitext-103/dict.txt
[19:47:44] Running knnlm_func.run_eval_ppl
Traceback (most recent call last):
  File "rq/fast_evaluate.py", line 266, in <module>
    main(args)
  File "rq/fast_evaluate.py", line 257, in main
    knnlm_func.run_eval_ppl(context)
  File "/work/hdd/bcyi/eergun/knnlm-retrieval-quality/rq/knnlm_func.py", line 43, in run_eval_ppl
    log_progress("get kNN probabilities")
  File "/work/hdd/bcyi/eergun/knnlm-retrieval-quality/rq/knnlm_func.py", line 6, in log_progress
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)
NameError: name 'time' is not defined
