Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/scratch/bcyi/esenergun/knnlm/lib/python3.8/site-packages/datasets/__init__.py", line 17, in <module>
    from .arrow_dataset import Dataset
  File "/scratch/bcyi/esenergun/knnlm/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 59, in <module>
    import pandas as pd
  File "/scratch/bcyi/esenergun/knnlm/lib/python3.8/site-packages/pandas/__init__.py", line 52, in <module>
    from pandas.core.api import (
  File "/scratch/bcyi/esenergun/knnlm/lib/python3.8/site-packages/pandas/core/api.py", line 15, in <module>
    from pandas.core.arrays import Categorical
  File "/scratch/bcyi/esenergun/knnlm/lib/python3.8/site-packages/pandas/core/arrays/__init__.py", line 7, in <module>
    from pandas.core.arrays.categorical import Categorical
  File "/scratch/bcyi/esenergun/knnlm/lib/python3.8/site-packages/pandas/core/arrays/categorical.py", line 57, in <module>
    from pandas.core.indexers import check_array_indexer, deprecate_ndim_indexing
ImportError: cannot import name 'deprecate_ndim_indexing' from 'pandas.core.indexers' (/scratch/bcyi/esenergun/knnlm/lib/python3.8/site-packages/pandas/core/indexers/__init__.py)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/scratch/bcyi/esenergun/knnlm/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/work/hdd/bcyi/eergun/knnlm-retrieval-quality/fairseq/data/dictionary.py", line 292, in _add_file_to_dictionary_single_worker
    with open(PathManager.get_local_path(filename), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/wikitext-103/wiki.train.tokens'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 11, in <module>
    cli_main()
  File "/work/hdd/bcyi/eergun/knnlm-retrieval-quality/fairseq_cli/preprocess.py", line 360, in cli_main
    main(args)
  File "/work/hdd/bcyi/eergun/knnlm-retrieval-quality/fairseq_cli/preprocess.py", line 95, in main
    src_dict = build_dictionary([train_path(args.source_lang)], src=True)
  File "/work/hdd/bcyi/eergun/knnlm-retrieval-quality/fairseq_cli/preprocess.py", line 61, in build_dictionary
    return task.build_dictionary(
  File "/work/hdd/bcyi/eergun/knnlm-retrieval-quality/fairseq/tasks/fairseq_task.py", line 69, in build_dictionary
    Dictionary.add_file_to_dictionary(filename, d, tokenizer.tokenize_line, workers)
  File "/work/hdd/bcyi/eergun/knnlm-retrieval-quality/fairseq/data/dictionary.py", line 329, in add_file_to_dictionary
    merge_result(r.get())
  File "/scratch/bcyi/esenergun/knnlm/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'data/wikitext-103/wiki.train.tokens'
